#!/usr/bin/python27

def throw_err():
	raise Exception("a error happen!")

throw_err()
